import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { FormEvent, useState } from "react";

import { api } from "~/utils/api";

const Poll: NextPage = () => {
  const router = useRouter();
  const pollId = router.query.pollId as string;

  const [selectedAnswer, setSelectedAnswer] = useState<string | undefined>();

  const { data: pollData, isLoading } = api.poll.getPoll.useQuery(
    { pollId },
    {
      enabled: !!pollId,
    }
  );

  const handlePollSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
  };

  return (
    <>
      <Head>
        <title>Answer a Poll</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        {isLoading ? (
          <>Loading...</>
        ) : (
          <section className="flex flex-col gap-6">
            <h1 className="text-3xl">{pollData?.prompt}</h1>
            <form onSubmit={handlePollSubmit}>
              {pollData?.answers?.map((answer) => {
                const answerId = `input-${answer.id}`;

                return (
                  <fieldset key={answer.id}>
                    <input
                      id={answerId}
                      type="radio"
                      checked={selectedAnswer === answer.id}
                      onChange={() => setSelectedAnswer(answer.id)}
                    />
                    <label htmlFor={answerId}>{answer.text}</label>
                  </fieldset>
                );
              })}

              <button
                className="mt-4 rounded bg-blue-700 p-3 text-white"
                type="submit"
              >
                Submit
              </button>
            </form>
          </section>
        )}
      </main>
    </>
  );
};

export default Poll;
